config/routes.rb
Rails.application.routes.draw do
  get 'checklists/new'

  post 'checklists/create'

  get 'index' => 'checklists/index'

  get 'checklists/edit'

  get 'checklists/delete'

  post 'checklists/update'
  
  delete 'checklists/destroy'

  post 'checklists/switch'

  get 'checklists/hpt'

  get 'checklists/cpt'
  
  resources :checklists

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'signup' => 'users#new'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'index' => 'checklists#index'

  root 'checklists#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checklist.rb
class Checklist < ApplicationRecord

  # A checklist is created by the user
  belongs_to :user

  # Validations
  validates :task_name, presence: true, length: {minimum: 5}
  validates :priority, presence: true, :inclusion => {:in => %w(High Medium Low)}

  # Per page setup for will_paginate
  self.per_page = 5

  # Scope to get High Priority Tasks
  scope :get_high_priority_tasks, -> { where(priority: 'High') }
  # Scope to get finished tasks
  scope :get_completed_tasks, -> { where(completed: true) }
  # Scope to get pending tasks
  scope :get_pending_tasks, ->{ where(completed: false) }

  def self.get_checklist_entries(user)
    user.checklists
  end

end

app/models/user.rb
class User < ApplicationRecord

  # uses bcrypt-ruby to generate secure passwords
  has_secure_password

  # A user can create many tasks
  has_many :checklists

  # Email regex that every user email should adhere to
  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # User model validation
  validates :first_name, presence: true, length: {maximum:20}
  validates :last_name, presence: true, length: {maximum: 20}
  validates :email, presence:true, length: {maximum: 200}, 
            format: {with: VALID_EMAIL}, uniqueness: true
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  # Checks if a user has logged in to the system
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # Will allow form navigations and task modifications only if the user is authorized to do that particular action
  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  
  # Check if a user session is active
  before_action :require_user
  # Check if current_user is the owner of a checklist before editing and deleting a task
  before_action :check_owner, only: [:edit, :destroy]

  def new
    @checklist = Checklist.new
  end

  # Invoked to create a new to-do task
  def create
    @checklist = Checklist.new(checklist_params)
    @checklist.user_id = current_user.id
    @checklist.completed = false
    if @checklist.save
      redirect_to '/checklists/index'
    else
      redirect_to '/checklists/new'
      flash[:notice] = "Error saving your Task. Task name is blank or shorter than 5 characters"
    end
  end

  # Gets all the pending tasks for a user
  def index
    @checklists = Checklist.get_checklist_entries(current_user).get_pending_tasks.paginate(page: params[:page])
  end

  # Gets all the pending high priority tasks
  def hpt
    @checklists = Checklist.get_checklist_entries(current_user).get_pending_tasks.get_high_priority_tasks.paginate(page: params[:page])
  end

  # Gets all the completed tasks
  def cpt
    @checklists = Checklist.get_checklist_entries(current_user).get_completed_tasks.paginate(page: params[:page])
  end

  # Allows a user to edit a task
  def edit
    @checklist = Checklist.find(params[:format])
  end

  def show
    redirect_to '/'
  end

  def update
    checklist = Checklist.find(params[:id])
    checklist.task_name = params[:checklist][:task_name]
    checklist.priority = params[:checklist][:priority]
    checklist.notes = params[:checklist][:notes]
    if checklist.save
      flash[:notice] = "Record updated successfully"
    else
      flash[:notice] = "Something went wrong!"
    end
    redirect_to '/'
  end

  # Deletes a task from the system
  def delete
    Checklist.find(params[:format]).destroy
    flash[:notice] = "Delete successful"
    redirect_to '/'
  end

  # Performs the owner check
  def check_owner
    if current_user != Checklist.find(params[:format]).user
      flash[:notice] = "Trying to be cheeky are we? You cannot modify a task that's not yours!"
      redirect_to '/'
    end
  end

  # If a task is complete, this function re-opens it and if a task is incomplete, this markes the task as complete.
  def switch
    @checklist = Checklist.find(params[:format])
    if @checklist.update_attribute(:completed, !@checklist.completed)
      flash[:notice] = "Status change successful"
    else
      flash[:notice] = "Something went wrong"
    end
    redirect_to '/'
  end


  private

  # Used for building a task from user's form input
  def checklist_params
    params.require(:checklist).permit(:task_name, :priority, :notes, :completed)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.where(email: params[:session][:email]).first
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.first_name}"
    else
      flash[:notice] = "Invalid credentials. Please try again"
    end
    redirect_to '/'
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully logged out of the system"
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  # Invoked when user cliks on sign up, uses the user_params method to build object.
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      @user.errors.messages.each do |name, msg|
        flash[name.to_sym] = "#{name}: #{msg.join(', ')}" 
      end
      redirect_to '/users/new'
    end 
  end

  private

  # Used for building a user object from user's form input
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checklists/_form.html.erb
<div class="container">
  <div class="row checklist-index">
    <div class="col-4">
      <span class="center">Task Name</span> 
    </div>
    <div class="col-4"
      <span class="center">Task Priority</span>
    </div>
    <div class="col-4 absolute-zero center"> Actions </div>
  </div>
  <%= will_paginate @checklists, page_links: false %>
  <% @checklists.each do |c| %>
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-4">
            <span class="center"><%= c.task_name %></span> 
          </div>
          <div class="col-4">
            <span class="center"><%= c.priority %></span>
          </div>
          <div class="col-4 absolute-zero"> 
            <%= link_to "Edit", checklists_edit_path(c), class: "btn btn-sm btn-primary" %> 
            <%= link_to "Mark as Complete", checklists_switch_path(c), method: :post, class: "btn btn-sm btn-success"  %> 
            <%= link_to "Delete", checklists_delete_path(c), class: "btn btn-sm btn-danger" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= will_paginate @checklists, page_links: false%> 
</div>

app/views/checklists/cpt.html.erb
<div class="center header-padding">
  <h5> <%= "Welcome " + current_user.first_name  %></h5>
</div>
<% if @checklists.present? %>
  <div class="container">
  <div class="row checklist-index">
    <div class="col-4">
      <span class="center">Task Name</span> 
    </div>
    <div class="col-4"
      <span class="center">Task Priority</span>
    </div>
    <div class="col-4 absolute-zero center"> Actions </div>
  </div>
  <%= will_paginate @checklists, page_links: false %>
  <% @checklists.each do |c| %>
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-4">
            <span class="center"><%= c.task_name %></span> 
          </div>
          <div class="col-4">
            <span class="center"><%= c.priority %></span>
          </div>
          <div class="col-4 center absolute-zero"> 
            <%= link_to "Reopen Task", checklists_switch_path(c), method: :post, class: "btn btn-sm btn-warning"  %> 
            <%= link_to "Delete", checklists_delete_path(c), class: "btn btn-sm btn-danger" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= will_paginate @checklists, page_links: false%> 
</div>
<% else %>
  <p> You don't have any Completed tasks in the system! </p> 
<%end%>
<%= link_to "View All Tasks", '/', class: "btn btn-primary btn-lg btn-block"%>

app/views/checklists/edit.html.erb
<div class="form-group">
  <%= render 'layouts/errors' %>
  <h5 class="center header-padding">Edit Task </h5>
  <%= form_for @checklist do |c| %>
    <%= c.label "Task Name*" %>
    <%= c.text_field :task_name, class: "form-control" %> <br/>
    <%= c.label "Priority*" %>
    <%= c.select :priority, ['High', 'Medium', 'Low'], class: "form-control"%> <br/>
    <%= c.label :notes%>
    <%= c.text_area :notes, class: "form-control" %> <br/>
    <span class="submit-form"><%= c.submit %></span>
  <%end%>
</div>

app/views/checklists/hpt.html.erb
<div class="center header-padding">
  <h5> <%= "Welcome " + current_user.first_name  %></h5>
</div>
<% if @checklists.present? %>
  <%= render 'checklists/form' %>
<% else %>
  <p> You don't have any High priority tasks in the system! </p> 
<%end%>
<%= link_to "View All Tasks", '/', class: "btn btn-primary btn-lg btn-block"%>

app/views/checklists/index.html.erb
<div class="center header-padding">
  <h5> <%= "Welcome " + current_user.first_name  %></h5>
</div>
<% if @checklists.present? %>
  <%= render 'checklists/form' %>
<% else %>
  <p> You don't have any Tasks in the system. Create by clikcing the button below! </p> 
<%end%>
<%= link_to "Create A Task", 'checklists/new', class: "btn btn-primary btn-lg btn-block"%>
<%= render 'layouts/errors' %>

app/views/checklists/new.html.erb
<div class="form-group">
  <%= render 'layouts/errors' %>
  <h5 class="center header-padding">Create a Task </h5>
  <%= form_for @checklist do |c| %>
    <%= c.label "Task Name*" %>
    <%= c.text_field :task_name, class: "form-control" %> <br/>
    <%= c.label "Priority*" %>
    <%= c.select :priority, ['High', 'Medium', 'Low'], class: "form-control"%> <br/>
    <%= c.label :notes%>
    <%= c.text_area :notes, class: "form-control" %> <br/>
    <span class="submit-form"><%= c.submit %></span>
  <%end%>
</div>

app/views/layouts/_errors.html.erb
<div class = "col-8 absolute-zero">
  <% flash.each do |name, msg| %>
    <%= content_tag :p, msg, class: "alert alert-info" %>
  <% end %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo List</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <a class="navbar-brand fontaroo" href="#"> ToDoList </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto white">
        </ul>
        <% if current_user %>
          <%= link_to current_user.email, '/' ,class: "white nav-link"%>
          <%= link_to "Log Out", '/logout', method: "delete", class: "white nav-link"%>
        <% else %>
          <%= link_to "Login", '/login', class: "white nav-link"%>
          <%= link_to "Sign Up", 'users/new', class: "white nav-link"%>
        <% end %>
      </div>
    </nav>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row row-height">
        <div class="col-sm- sidebar-sticky">
          <% if current_user %>
            <%= link_to "Create a Task", "/checklists/new", class: "nav-link btn-outline-secondary center" %>
            <%= link_to "High Priority Tasks", "/checklists/hpt", class: "nav-link btn-outline-secondary center" %>
            <%= link_to "Completed Tasks", "/checklists/cpt", class: "nav-link btn-outline-secondary center" %>
          <% end %>
        </div>
        <div class='col-lg- position-relative form-width padded-container'>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/new.html.erb
<div class="form-group">
  <%= render 'layouts/errors' %>
  <h5 class="center header-padding">Sign Up </h5>
  <%= form_for @user do |f| %>
  	<%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %> <br/>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %> <br/>
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %> <br/>
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %> <br/>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control"%> <br/>
    <span class="submit-form"><%= f.submit %> </span>
  <% end %>
</div>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= current_user.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= current_user.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= current_user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password_digest) %>:</strong></dt>
  <dd><%= current_user.password_digest %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(current_user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(current_user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>